### ISSUE TITLE
ctx.accept('type', undefined);

### ISSUE THREAD

**Issue by yanickrochon** [rse/tokenizr#1]
The method `ctx.accept` should *not* blindly default on falsy values, and should check the number of arguments instead.

```
ctx.accept('keyword', undefined);
```

should set the token value to `undefined`, and **not** `'undefined'`.

**Comment by rse** [comment]
Thanks for the hint. Now fixed.

**Comment by yanickrochon** [comment]
Awesome! Thanks!
