### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by kevinkhill** [rse/tokenizr#11]
I didn't make a direct fork so I guess it didn't show on here, but, what do you think of this? I saw you just posted a types file and I got pinged. 

https://github.com/kevinkhill/ts-tokenizr

**Comment by bradkovach** [comment]
This already has types included, so in order to use with typescript, you just need to add the following to compilerOptions

```json
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
```
