### ISSUE TITLE
Can a term accepting 2 types values?

### ISSUE THREAD

**Issue by Tyre20** [rse/tokenizr#9]
For a string e.g I am a boy and I live in Chicago can I set a rule for boy term to be both ctx.accept(“male”) as well as the a boy (“one person”)? The boy appear twice and and I want it’s type to be bother male and one person

**Comment by kevinkhill** [comment]
That sounds more like a job for  the parser to apply context to the tokens than creating them.

But I could be 100% wrong

**Comment by rse** [comment]
Yes, indeed, I also think this is a job for the parser on top of Tokenizr. A tokenizer just groups characters to tokens, and does not judge on the semantic of a token.
